# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: go-tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions: {}

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      stable: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}
      previous: ${{ steps.versions.outputs.GO_MINOR_VERSION_PREVIOUS }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Determine Go versions
      id: versions
      uses: carabiner-dev/actions/go/versions@486750c75e9c3900944193c0c2d7956a840acf2a # main

  test:
    needs: go-versions
    permissions:
      contents: read

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - ${{ needs.go-versions.outputs.previous }}
          - ${{ needs.go-versions.outputs.stable }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true

    - name: Test
      run: |
        go get -d ./...
        go test -v ./...
